export const endPoints={
    GET_USER_INITIAL_DATA: '/users/profile',
    UPDATE_LANDING_PAGE: '/users/update_landing_page',
    GET_PROFILE_API: 'users/get_profile',
    UPDATE_PROFILE_API: 'users/update_profile',
    GET_CITY_SEARCH_API:'users/city_suggestions',
    GET_CAR_IMAGE_API:'users/car_image',
    CREATE_TRIP_API:'users/create_trip',
    CREATE_TWO_WAY_API:'users/create_two_way_trip',
    DRIVER_ARRIVAL_TIME:'users/trip/driver-arrival-info',
    // GET_CITY_SEARCH_API:'/drivers/city_suggestions',
    UPDATE_DRIVER_PROFILE: 'drivers/register_driver',
    UPDATE_USER_PROFILE:'users/register_user',
    UPLOAD_PROFILE_IMAGE:'users/upload_profile_image',
    UPLOAD_DRIVER_PROFILE_IMAGE:'drivers/upload_driver_profile_image',
    GET_DRIVER_PAYMENT_TRANSACTIONS:'drivers/transaction',
    GET_DRIVER_BOOKING_DETAILS: 'drivers/booking_details',
    GET_DRIVER_BANK_DETAILS: 'drivers/bank_details',
    GET_DRIVER_BOOKING_OWNER_DETAILS: 'drivers/on_view/owner_details',
    SUBMIT_CAR_DETAILS_API:'users/register_car',
    SUBMIT_DRIVING_DETAILS_API:'drivers/register_driver_details',
    SUBMIT_DRIVER_BANK_DETAILS:'drivers/bank_details_for_driver',
    GET_CAR_MODEL_SEARCH_API:'users/car_model_suggestions',
    GET_TRIP_DETAILS:'users/tripdetails/tripId',
    GET_OWNER_ACTIVE_TRIP:'users/getOwnerActiveTrip',
    EDIT_OWNER_ACCOUNT_DETAILS:'users/users/update_profile',
    EDIT_DRIVER_ACCOUNT_DETAILS:'drivers/driver/update_account',
    GET_OWNER_CARS_API:'users/user',
    DELETE_CAR_API:'users/delete_car',  
    UPDATE_CAR_API:'users/update_car',
    SAVE_OTP_API:'users/save_otp',
    UPDATE_DRIVER_INTEREST:'drivers/driver_interest/reject/update',
    UPDATE_DRIVER_CONFIRM_INTEREST:'drivers/driver_interest/confirm/update',
    GET_PAYMENT_HISTORY:'users/trip/payments',
    GET_DRIVER_BOOKING_HISTORY:'drivers/bookinghistory/driver',
    GET_DRIVER_CONFIRMED_TRIP_DETAILS:'drivers/confirmed/trip_details',
    // SAVE_OTP_API:'users/save_otp',
    Validate_OTP:'drivers/validate_otp' , 
    GET_OTP_API:'users/get_otp',
    GET_DRIVER_REG_DETAILS:'drivers/get_driver_reg',
    POST_TRIP_STATUS:'drivers/update_trip_status',
    // UPDATE_DRIVER_INTEREST:'drivers/driver-interest/update',
    // SUBMIT_DRIVING_DETAILS_API:'drivers/register_driver_details',
    // SUBMIT_DRIVING_DETAILS_API:'drivers/register_driver_details',
    UPDATE_DRIVER_ACTIVE_STATUS : 'drivers/update_active_status',
    GET_INTERESTED_DRIVERS_API:'users/interested-drivers',
    GET_DRIVER_STATUS:'drivers/get_driver_status',
    CONFIRM_DRIVER_API:'users/confirm_driver',
    GET_TRIP_DETAILS_STATUS:'users/tripdetails/by-status',
    POST_MAIL_TICKET:'mail/support',
    GET_NEAR_BY_DRIVERS:'users/search-nearby',
    GET_ALL_ADMIN_OWNER:'admin/getAllOwners',
    GET_ALL_ADMIN_DRIVER:'admin/getAllDrivers',
    GET_ADMIN_DRIVER_BY_ID: 'admin/getDriverbyId',
    GET_ADMIN_OWNER_BY_ID: 'admin/getOwnerbyId',
    UPDATE_DRIVER_BY_ID:'admin/updateDriver',
    UPDATE_OWNER_BY_ID:'admin/updateOwner',
    GET_DRIVER_CONFIG:'admin/getConfig',
    UPDATE_DRIVER_CONFIG:'admin/updateConfig',
    UPDATE_CAR_PRIMARY:'users/car',
    GET_DRIVER_PROFILE_API:'drivers/driver',
    CALCULATE_FARE:'users/calculate-fare',
    UPDATE_DRIVER_LIVE_LOCATION:'users/update-driver-live-location', 
    GET_ALL_ADMIN:'admin/getAllAdmin',
    CREATE_ADMIN: "admin/createAdmin",
    UPDATE_ADMIN: "admin/updateAdmin",
    DELETE_ADMIN: "admin/deleteAdmin",
    GET_DRIVER_BALANCE:'drivers/driver_balance',
    GET_ONEWAY_TRIPS: "admin/getAllOnewayTrips", 
    GET_ALL_TRIPS: "admin/getAllTrips", 
    UPDATE_DRIVER_ALLOWANCE: "admin/updateDriverAllowance",
    END_TRIP:"users/trip/end",
    GET_ALL_REPORTS: "admin/getAllReport",
    GET_REPORT_BY_ID: "admin/getReportById",
    GET_DRIVER_TRIP_FARE:'drivers/get_trip_fare',
    GET_DASHBOARD_TOTAL:'admin/getDashboardTotal',
    GET_DRIVER_TRIP_STATUS:'drivers/get_trip_status',
    CREATE_ORDER: "users/create-payment-order",
    VERIFY_PAYMENT : "users/verify-payment",
    UPLOAD_DOCUMENT_API: "auth/upload_document",
    GET_ANNOUNCEMENTS: "users/announcement",
    DELETE_USER_ACCOUNT:"users/delete-account",
    UPLOAD_CAR_TRIPS: 'drivers/uploadCarTrips'
    
    
}
    
    