
const routes = {
  HOME_PAGE: '/home',
  BOOKING_PAGE: '/booking',
  PROFILE_PAGE: '/profile',
  CAR_DETAILS: '/cardetails',
  LOGIN_PAGE:'/login',
  OTP_PAGE: '/otp',
  LOOKING_FOR_PAGE:'/LookingForPage',
  NETWORK_ERROR_PAGE: '/networkError',
  DRIVER_PAYMENT_PAGE: '/driver-payment',
  DRIVER_BOOKING_VIEW_PAGE :'/booking/view',
  DRIVER_BOOKING_ACCEPT_PAGE :'/booking/accept',
  DRIVER_PAYMENT_WITHDRAW_PAGE : '/driver-payment/withdraw',
  DRIVER_PAYMENT_WITHDRAW_COMPLETE_PAGE : '/driver-payment/withdraw/complete',
  // PAYMENT_PAGE: '/payment',
  MANAGE_CAR_DETAILS:'/manageCarDetails',
  OWNER_ACCOUNT_DETAILS_PAGE:'/owneraccountdetails',
  OWNER_PAYMENT_HISTORY_PAGE:'/ownerpaymenthistory',
  ACCOUNT_DETAILS_PAGE:"/account-details",
  BOOKING_HISTORY_PAGE:"/bookinghistory",
  DRIVER_BOOKING_HISTORY_PAGE:'/driverbookinghistory',
  DRIVER_TRIP_PAYMENT_SUMMARY_PAGE:'/driver/trip_payment/summary',
  BOOKING_VIEW_PAGE :'/booking/view/:id',
  DRIVER_PROFILE_FORM_PAGE: '/driver_profile_form',
  DRIVER_DETAIL_FORM_PAGE: '/driver_detail_page',
  DRIVER_BANK_FORM_PAGE: '/driver_bank_detail_page',
  OWNER_PROFILE_FORM_PAGE: '/car_owner_profile_form',
  OWNER_CAR_DETAIL_FORM_PAGE: '/cardetails',
  OWNER_PROFILE_PAGE: '/owner-profile',
  INTERESTED_DRIVER_PAGE:'/interested-drivers',
  SEARCH_DRIVER_RANGE_BASED_PAGE : '/search-drivers',
  ADMIN_CONFIGURE_PAGE: '/configure',
  ADMIN_REPORT_PAGE: '/report',
  ADMIN_ROLES_PAGE: '/roles',
  ADMIN_TRIPS_PAGE: '/trips',
  CREATE_TRIP_PAGE:'/rent-your-driver',
  OWNER_PAYMENT_DETAILS_PAGE:'/payment-details/:id',
  ADMIN_INDIVIDUAL_DRIVER_PAGE: '/approval/get-driver-details/:id',
  ADMIN_INDIVIDUAL_OWNER_PAGE: '/approval/get-owner-details/:id',
  DRIVER_PAYMENT_DONE_PAGE:'/payment-success',
  ADMIN_APPROVAL_PAGE: '/approval',
  DRIVER_PROFILE_PAGE:'/driver-profile',
  UNAUTHORIZED_PAGE:'/unauthorized',
  ADMIN_REPORT_DETAILS_VIEW: '/report/details-view/:type/:id',
  DELETE_ACCOUNT_PAGE:'/delete',
};

export default routes;

